#ifndef YHGE_ENTITYCOMPONENT_COMPONENTS_MESSAGES_H_
#define YHGE_ENTITYCOMPONENT_COMPONENTS_MESSAGES_H_

#include <yhge/YHGEMacros.h>

NS_CC_YHGE_BEGIN

//message id从10000开始
enum
{
    //attack
    MSG_ANIMATION=10000,
    MSG_CHANGE_ANIMATION,
    //attack
    MSG_ATTACK,
    MSG_SET_ATTACK_TARGET,
    MSG_AUTO_ATTACK,
    MSG_TARGET_DIE,
    //move
    MSG_MOVE_TO,
    MSG_MOVE_DIRECTION,
    MSG_MOVE_DIRECTION_TO,
    MSG_MOVE_DIRECTION_STOP,
	MSG_MOVE_PATH,
    MSG_MOVE_PATH_FROM,
    MSG_MOVE_STOP,
    //sprite renderer
    MSG_RUN_ACTION,
    MSG_STOP_ACTION,
    MSG_STOP_ACTION_BY_TAG,
    //position
    MSG_POSITION_CHANGE,
    //entity
    MSG_ENTITY_DIE
};

NS_CC_YHGE_END

#endif //YHGE_ENTITYCOMPONENT_COMPONENTS_MESSAGES_H_
