#ifndef YHGE_ENTITYCOMPONENT_COMPONENTS_COMPONENTCONSTS_H_
#define YHGE_ENTITYCOMPONENT_COMPONENTS_COMPONENTCONSTS_H_


#define COMPONENT_ANIMATION_CHANGE_PARAM_TYPE "type"
#define COMPONENT_ANIMATION_CHANGE_PARAM_NAME "name"
#define COMPONENT_ANIMATION_CHANGE_PARAM_DIRECTION "direction"

#define COMPONENT_GRID_MOVE_RARAM_PATHS "paths"
#define COMPONENT_GRID_MOVE_RARAM_FROMINDEX "fromIndex"

//#include <yhge/YHGEMacros.h>
//
//NS_CC_YHGE_BEGIN
//
//
//NS_CC_YHGE_END

#endif //YHGE_ENTITYCOMPONENT_COMPONENTS_COMPONENTCONSTS_H_
